const sequelize = require('../config/database');
const Spell = require('../models/Spell');

/**
 * Traducción al español de los NOMBRES de conjuros del SRD (hecha a mano,
 * terminología D&D). Se guarda en translation.name. Idempotente.
 */
const NAMES_ES = {
    'Acid Arrow': 'Flecha Ácida',
    'Acid Splash': 'Salpicadura Ácida',
    'Aid': 'Auxilio',
    'Alarm': 'Alarma',
    'Alter Self': 'Alterar el Propio Ser',
    'Animal Friendship': 'Amistad Animal',
    'Animal Messenger': 'Mensajero Animal',
    'Animal Shapes': 'Formas Animales',
    'Animate Dead': 'Animar a los Muertos',
    'Animate Objects': 'Animar Objetos',
    'Antilife Shell': 'Caparazón Antivida',
    'Antimagic Field': 'Campo Antimagia',
    'Antipathy/Sympathy': 'Antipatía/Simpatía',
    'Arcane Eye': 'Ojo Arcano',
    'Arcane Hand': 'Mano Arcana',
    'Arcane Lock': 'Cerradura Arcana',
    'Arcane Sword': 'Espada Arcana',
    "Arcanist's Magic Aura": 'Aura Mágica del Arcanista',
    'Astral Projection': 'Proyección Astral',
    'Augury': 'Augurio',
    'Awaken': 'Despertar',
    'Bane': 'Perdición',
    'Banishment': 'Destierro',
    'Barkskin': 'Piel de Corteza',
    'Beacon of Hope': 'Faro de Esperanza',
    'Bestow Curse': 'Infligir Maldición',
    'Black Tentacles': 'Tentáculos Negros',
    'Blade Barrier': 'Barrera de Cuchillas',
    'Bless': 'Bendecir',
    'Blight': 'Plaga',
    'Blindness/Deafness': 'Ceguera/Sordera',
    'Blink': 'Parpadeo',
    'Blur': 'Difuminar',
    'Branding Smite': 'Castigo Marcador',
    'Burning Hands': 'Manos Ardientes',
    'Call Lightning': 'Llamar a los Relámpagos',
    'Calm Emotions': 'Calmar Emociones',
    'Chain Lightning': 'Relámpago en Cadena',
    'Charm Person': 'Hechizar Persona',
    'Chill Touch': 'Toque Escalofriante',
    'Circle of Death': 'Círculo de Muerte',
    'Clairvoyance': 'Clarividencia',
    'Clone': 'Clon',
    'Cloudkill': 'Nube Mortal',
    'Color Spray': 'Rociada de Color',
    'Command': 'Orden',
    'Commune': 'Comunión',
    'Commune with Nature': 'Comunión con la Naturaleza',
    'Comprehend Languages': 'Comprender Idiomas',
    'Compulsion': 'Compulsión',
    'Cone of Cold': 'Cono de Frío',
    'Confusion': 'Confusión',
    'Conjure Animals': 'Convocar Animales',
    'Conjure Celestial': 'Convocar Celestial',
    'Conjure Elemental': 'Convocar Elemental',
    'Conjure Fey': 'Convocar Hada',
    'Conjure Minor Elementals': 'Convocar Elementales Menores',
    'Conjure Woodland Beings': 'Convocar Seres del Bosque',
    'Contact Other Plane': 'Contactar con Otro Plano',
    'Contagion': 'Contagio',
    'Contingency': 'Contingencia',
    'Continual Flame': 'Llama Continua',
    'Control Water': 'Controlar el Agua',
    'Control Weather': 'Controlar el Clima',
    'Counterspell': 'Contrahechizo',
    'Create Food and Water': 'Crear Comida y Agua',
    'Create or Destroy Water': 'Crear o Destruir Agua',
    'Create Undead': 'Crear No Muerto',
    'Creation': 'Creación',
    'Cure Wounds': 'Curar Heridas',
    'Dancing Lights': 'Luces Danzantes',
    'Darkness': 'Oscuridad',
    'Darkvision': 'Visión en la Oscuridad',
    'Daylight': 'Luz del Día',
    'Death Ward': 'Salvaguarda contra la Muerte',
    'Delayed Blast Fireball': 'Bola de Fuego de Explosión Retardada',
    'Demiplane': 'Semiplano',
    'Detect Evil and Good': 'Detectar el Bien y el Mal',
    'Detect Magic': 'Detectar Magia',
    'Detect Poison and Disease': 'Detectar Venenos y Enfermedades',
    'Detect Thoughts': 'Detectar Pensamientos',
    'Dimension Door': 'Puerta Dimensional',
    'Disguise Self': 'Disfrazarse',
    'Disintegrate': 'Desintegrar',
    'Dispel Evil and Good': 'Disipar el Bien y el Mal',
    'Dispel Magic': 'Disipar Magia',
    'Divination': 'Adivinación',
    'Divine Favor': 'Favor Divino',
    'Divine Word': 'Palabra Divina',
    'Dominate Beast': 'Dominar Bestia',
    'Dominate Monster': 'Dominar Monstruo',
    'Dominate Person': 'Dominar Persona',
    'Dream': 'Sueño',
    'Druidcraft': 'Truco Druídico',
    'Earthquake': 'Terremoto',
    'Eldritch Blast': 'Descarga Sobrenatural',
    'Enhance Ability': 'Mejorar Característica',
    'Enlarge/Reduce': 'Agrandar/Reducir',
    'Entangle': 'Enredar',
    'Enthrall': 'Cautivar',
    'Etherealness': 'Etereidad',
    'Expeditious Retreat': 'Retirada Expeditiva',
    'Eyebite': 'Mal de Ojo',
    'Fabricate': 'Fabricar',
    'Faerie Fire': 'Fuego Feérico',
    'Faithful Hound': 'Sabueso Fiel',
    'False Life': 'Falsa Vida',
    'Fear': 'Miedo',
    'Feather Fall': 'Caída de Pluma',
    'Feeblemind': 'Debilidad Mental',
    'Find Familiar': 'Encontrar Familiar',
    'Find Steed': 'Encontrar Montura',
    'Find the Path': 'Encontrar el Camino',
    'Find Traps': 'Encontrar Trampas',
    'Finger of Death': 'Dedo de la Muerte',
    'Fire Bolt': 'Descarga de Fuego',
    'Fire Shield': 'Escudo de Fuego',
    'Fire Storm': 'Tormenta de Fuego',
    'Fireball': 'Bola de Fuego',
    'Flame Blade': 'Hoja Llameante',
    'Flame Strike': 'Columna de Fuego',
    'Flaming Sphere': 'Esfera Flamígera',
    'Flesh to Stone': 'Carne a Piedra',
    'Floating Disk': 'Disco Flotante',
    'Fly': 'Volar',
    'Fog Cloud': 'Nube de Niebla',
    'Forbiddance': 'Prohibición',
    'Forcecage': 'Jaula de Fuerza',
    'Foresight': 'Presciencia',
    'Freedom of Movement': 'Libertad de Movimiento',
    'Freezing Sphere': 'Esfera Congeladora',
    'Gaseous Form': 'Forma Gaseosa',
    'Gate': 'Portal',
    'Geas': 'Geas',
    'Gentle Repose': 'Reposo Apacible',
    'Giant Insect': 'Insecto Gigante',
    'Glibness': 'Labia',
    'Globe of Invulnerability': 'Globo de Invulnerabilidad',
    'Glyph of Warding': 'Glifo de Protección',
    'Goodberry': 'Baya Nutritiva',
    'Grease': 'Grasa',
    'Greater Invisibility': 'Invisibilidad Superior',
    'Greater Restoration': 'Restauración Mayor',
    'Guardian of Faith': 'Guardián de la Fe',
    'Guards and Wards': 'Guardias y Salvaguardas',
    'Guidance': 'Guía',
    'Guiding Bolt': 'Rayo Guía',
    'Gust of Wind': 'Ráfaga de Viento',
    'Hallow': 'Santificar',
    'Hallucinatory Terrain': 'Terreno Alucinatorio',
    'Harm': 'Dañar',
    'Haste': 'Prisa',
    'Heal': 'Sanar',
    'Healing Word': 'Palabra Curativa',
    'Heat Metal': 'Calentar Metal',
    'Hellish Rebuke': 'Reproche Infernal',
    "Heroes' Feast": 'Festín de Héroes',
    'Heroism': 'Heroísmo',
    'Hideous Laughter': 'Risa Horrible',
    'Hold Monster': 'Inmovilizar Monstruo',
    'Hold Person': 'Inmovilizar Persona',
    'Holy Aura': 'Aura Sagrada',
    "Hunter's Mark": 'Marca del Cazador',
    'Hypnotic Pattern': 'Patrón Hipnótico',
    'Ice Storm': 'Tormenta de Hielo',
    'Identify': 'Identificar',
    'Illusory Script': 'Escritura Ilusoria',
    'Imprisonment': 'Encarcelamiento',
    'Incendiary Cloud': 'Nube Incendiaria',
    'Inflict Wounds': 'Infligir Heridas',
    'Insect Plague': 'Plaga de Insectos',
    'Instant Summons': 'Convocación Instantánea',
    'Invisibility': 'Invisibilidad',
    'Irresistible Dance': 'Danza Irresistible',
    'Jump': 'Saltar',
    'Knock': 'Llamar',
    'Legend Lore': 'Saber Legendario',
    'Lesser Restoration': 'Restauración Menor',
    'Levitate': 'Levitar',
    'Light': 'Luz',
    'Lightning Bolt': 'Relámpago',
    'Locate Animals or Plants': 'Localizar Animales o Plantas',
    'Locate Creature': 'Localizar Criatura',
    'Locate Object': 'Localizar Objeto',
    'Longstrider': 'Zancada Larga',
    'Mage Armor': 'Armadura de Mago',
    'Mage Hand': 'Mano de Mago',
    'Magic Circle': 'Círculo Mágico',
    'Magic Jar': 'Receptáculo Mágico',
    'Magic Missile': 'Proyectil Mágico',
    'Magic Mouth': 'Boca Mágica',
    'Magic Weapon': 'Arma Mágica',
    'Magnificent Mansion': 'Mansión Magnífica',
    'Major Image': 'Imagen Mayor',
    'Mass Cure Wounds': 'Curar Heridas en Masa',
    'Mass Heal': 'Sanar en Masa',
    'Mass Healing Word': 'Palabra Curativa en Masa',
    'Mass Suggestion': 'Sugestión en Masa',
    'Maze': 'Laberinto',
    'Meld into Stone': 'Fundirse con la Piedra',
    'Mending': 'Reparar',
    'Message': 'Mensaje',
    'Meteor Swarm': 'Enjambre de Meteoros',
    'Mind Blank': 'Mente en Blanco',
    'Minor Illusion': 'Ilusión Menor',
    'Mirage Arcane': 'Espejismo Arcano',
    'Mirror Image': 'Imagen Especular',
    'Mislead': 'Despistar',
    'Misty Step': 'Paso Brumoso',
    'Modify Memory': 'Modificar Memoria',
    'Moonbeam': 'Rayo de Luna',
    'Move Earth': 'Mover Tierra',
    'Nondetection': 'Indetectabilidad',
    'Pass without Trace': 'Pasar sin Dejar Rastro',
    'Passwall': 'Pasamuros',
    'Phantasmal Killer': 'Asesino Fantasmal',
    'Phantom Steed': 'Montura Fantasmal',
    'Planar Ally': 'Aliado Planar',
    'Planar Binding': 'Atadura Planar',
    'Plane Shift': 'Cambio de Plano',
    'Plant Growth': 'Crecimiento Vegetal',
    'Poison Spray': 'Rociada de Veneno',
    'Polymorph': 'Metamorfosis',
    'Power Word Kill': 'Palabra de Poder: Matar',
    'Power Word Stun': 'Palabra de Poder: Aturdir',
    'Prayer of Healing': 'Plegaria de Curación',
    'Prestidigitation': 'Prestidigitación',
    'Prismatic Spray': 'Rociada Prismática',
    'Prismatic Wall': 'Muro Prismático',
    'Private Sanctum': 'Santuario Privado',
    'Produce Flame': 'Producir Llama',
    'Programmed Illusion': 'Ilusión Programada',
    'Project Image': 'Proyectar Imagen',
    'Protection from Energy': 'Protección contra la Energía',
    'Protection from Evil and Good': 'Protección contra el Bien y el Mal',
    'Protection from Poison': 'Protección contra el Veneno',
    'Purify Food and Drink': 'Purificar Comida y Bebida',
    'Raise Dead': 'Levantar a los Muertos',
    'Ray of Enfeeblement': 'Rayo de Debilitamiento',
    'Ray of Frost': 'Rayo de Escarcha',
    'Regenerate': 'Regenerar',
    'Reincarnate': 'Reencarnar',
    'Remove Curse': 'Levantar Maldición',
    'Resilient Sphere': 'Esfera Resistente',
    'Resistance': 'Resistencia',
    'Resurrection': 'Resurrección',
    'Reverse Gravity': 'Invertir Gravedad',
    'Revivify': 'Revivir',
    'Rope Trick': 'Truco de la Cuerda',
    'Sacred Flame': 'Llama Sagrada',
    'Sanctuary': 'Santuario',
    'Scorching Ray': 'Rayo Abrasador',
    'Scrying': 'Visión Lejana',
    'Secret Chest': 'Cofre Secreto',
    'See Invisibility': 'Ver lo Invisible',
    'Seeming': 'Apariencia',
    'Sending': 'Envío',
    'Sequester': 'Aislar',
    'Shapechange': 'Cambiar de Forma',
    'Shatter': 'Destrozar',
    'Shield': 'Escudo',
    'Shield of Faith': 'Escudo de Fe',
    'Shillelagh': 'Garrote Mágico',
    'Shocking Grasp': 'Contacto Electrizante',
    'Silence': 'Silencio',
    'Silent Image': 'Imagen Silenciosa',
    'Simulacrum': 'Simulacro',
    'Sleep': 'Dormir',
    'Sleet Storm': 'Tormenta de Aguanieve',
    'Slow': 'Lentitud',
    'Spare the Dying': 'Perdonar al Moribundo',
    'Speak with Animals': 'Hablar con Animales',
    'Speak with Dead': 'Hablar con los Muertos',
    'Speak with Plants': 'Hablar con Plantas',
    'Spider Climb': 'Trepar como Araña',
    'Spike Growth': 'Crecimiento de Púas',
    'Spirit Guardians': 'Guardianes Espirituales',
    'Spiritual Weapon': 'Arma Espiritual',
    'Stinking Cloud': 'Nube Hedionda',
    'Stone Shape': 'Moldear Piedra',
    'Stoneskin': 'Piel de Piedra',
    'Storm of Vengeance': 'Tormenta de Venganza',
    'Suggestion': 'Sugestión',
    'Sunbeam': 'Rayo de Sol',
    'Sunburst': 'Estallido Solar',
    'Symbol': 'Símbolo',
    'Telekinesis': 'Telequinesis',
    'Telepathic Bond': 'Vínculo Telepático',
    'Teleport': 'Teletransporte',
    'Teleportation Circle': 'Círculo de Teletransporte',
    'Thaumaturgy': 'Taumaturgia',
    'Thunderwave': 'Onda Atronadora',
    'Time Stop': 'Detener el Tiempo',
    'Tiny Hut': 'Choza Diminuta',
    'Tongues': 'Lenguas',
    'Transport via Plants': 'Transporte Vegetal',
    'Tree Stride': 'Paso Arbóreo',
    'True Polymorph': 'Metamorfosis Verdadera',
    'True Resurrection': 'Resurrección Verdadera',
    'True Seeing': 'Visión Verdadera',
    'True Strike': 'Golpe Certero',
    'Unseen Servant': 'Sirviente Invisible',
    'Vampiric Touch': 'Toque Vampírico',
    'Vicious Mockery': 'Burla Cruel',
    'Wall of Fire': 'Muro de Fuego',
    'Wall of Force': 'Muro de Fuerza',
    'Wall of Ice': 'Muro de Hielo',
    'Wall of Stone': 'Muro de Piedra',
    'Wall of Thorns': 'Muro de Espinas',
    'Warding Bond': 'Vínculo Protector',
    'Water Breathing': 'Respiración Acuática',
    'Water Walk': 'Caminar sobre el Agua',
    'Web': 'Telaraña',
    'Weird': 'Espanto',
    'Wind Walk': 'Andar en el Viento',
    'Wind Wall': 'Muro de Viento',
    'Wish': 'Deseo',
    'Word of Recall': 'Palabra de Retorno',
    'Zone of Truth': 'Zona de Verdad',
};

/** Aplica el mapa: guarda translation.name en cada conjuro. Idempotente. */
async function seedSpellNamesEs() {
    const names = Object.keys(NAMES_ES);
    const spells = await Spell.findAll({ where: { name: names } });
    let updated = 0;
    for (const s of spells) {
        const es = NAMES_ES[s.name];
        if (es && !(s.translation && s.translation.name === es)) {
            s.translation = { ...(s.translation || {}), name: es };
            await s.save();
            updated++;
        }
    }
    console.log(`Nombres de conjuro (ES): ${updated} actualizados de ${Object.keys(NAMES_ES).length}.`);
    return updated;
}

module.exports = { seedSpellNamesEs, NAMES_ES };

if (require.main === module) {
    require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
    (async () => {
        try {
            await sequelize.authenticate();
            await seedSpellNamesEs();
            process.exit(0);
        } catch (e) {
            console.error('Error:', e.message);
            process.exit(1);
        }
    })();
}
